$LOAD_PATH.unshift "#{ENV['PROJECT_X_BASE']}/lib/"
require "test/unit"
require "fileutils"
require "spandex/application"
require "spandex/card"
require "spandex/list"
require "spandex/assertions"
require "honcho/message"
